#!/usr/bin/expect

# Author : CABOS Matthieu
# Date : 21/10/2021

set timeout 2

set splitted [lindex $argv 0]
set count 0
spawn ./base_alternative_v2_solveur

foreach item $splitted {
	if { $count == 0 } {
		set txt $item
		set count 1
	} else {
		set key $item
		set count 0
		expect "chaine cryptée : "
		send $txt
		send "\r"
		expect "clé : "
		send $key
		send "\r"
		expect "c)ontinuer ou q)uitter
"
		send "c\r"
	}
}